import Link from "next/link";
import { notFound } from "next/navigation";
import { PortalMessages } from "@/components/portal/PortalMessages";
import { getPortalCase } from "@/server/services/portal-service";

export default async function ClientCasePage({ params }: { params: { caseId: string } }) {
  const caseItem = await getPortalCase(params.caseId); if (!caseItem) notFound();
  return <div><Link href="/portal" className="text-sm font-medium text-brand-700">Back to cases</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">{caseItem.title}</h1><p className="mt-1 text-sm text-neutral-600">{caseItem.streamLabel} · {caseItem.status.replaceAll("_", " ")}</p></div><div className="flex gap-2"><Link href={`/portal/cases/${caseItem.id}/intake`} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm font-medium">Intake</Link><Link href={`/portal/cases/${caseItem.id}/documents`} className="rounded-lg bg-brand-600 px-3 py-2 text-sm font-medium text-white">Documents</Link></div></div><section className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-neutral-200 bg-white p-4"><p className="text-xs text-neutral-500">Checklist</p><p className="mt-1 text-lg font-semibold">{caseItem.checklistCompleted}/{caseItem.checklistTotal}</p></div><div className="rounded-lg border border-neutral-200 bg-white p-4"><p className="text-xs text-neutral-500">Current milestone</p><p className="mt-1 text-sm font-semibold">{caseItem.currentMilestone.replaceAll("_", " ")}</p></div><div className="rounded-lg border border-neutral-200 bg-white p-4"><p className="text-xs text-neutral-500">Case team</p><p className="mt-1 text-sm font-semibold">{caseItem.team.join(", ") || "Assigned team"}</p></div></section><section className="mt-6 rounded-lg border border-neutral-200 bg-white"><div className="border-b border-neutral-200 px-5 py-4"><h2 className="text-base font-semibold">Required documents</h2></div><ul className="divide-y divide-neutral-200">{caseItem.requirements.filter((item) => item.required).map((item) => <li key={item.id} className="flex items-center justify-between gap-4 px-5 py-3"><span className="text-sm">{item.label}</span><span className="text-xs font-medium text-neutral-600">{item.status.replaceAll("_", " ")}</span></li>)}</ul></section>{caseItem.deadlines.length ? <section className="mt-6 rounded-lg border border-neutral-200 bg-white p-5"><h2 className="text-base font-semibold">Deadlines</h2>{caseItem.deadlines.map((deadline) => <p key={deadline.id} className="mt-2 text-sm text-neutral-700">{deadline.label}: {new Date(deadline.dueDate).toLocaleDateString()}</p>)}</section> : null}<div className="mt-6"><PortalMessages caseId={caseItem.id} initialMessages={caseItem.messages} /></div></div>;
}
